{
    psiImplUtilClass="ru.bellski.lang.metasql.util.MetaSqlPsiImplUtil"

    parserClass="ru.bellski.lang.metasql.MetaSqlParser"
    parserUtilClass="ru.bellski.lang.metasql.psi.impl.MetaSqlGeneratedParserUtilBase"

    implements="ru.bellski.lang.metasql.psi.MetaSqlPsiCompositeElement"
    extends="ru.bellski.lang.metasql.psi.impl.MetaSqlPsiCompositeElementImpl"

    psiClassPrefix="MetaSql"
    psiImplClassSuffix="Impl"
    psiPackage="ru.bellski.lang.metasql.psi"
    psiImplPackage="ru.bellski.lang.metasql.psi.impl"

    elementTypeHolderClass="ru.bellski.lang.metasql.MetaSqlTokenTypes"
    elementTypePrefix=""
    elementTypeClass="ru.bellski.lang.metasql.MetaSqlElementType"
    tokenTypeClass="ru.bellski.lang.metasql.MetaSqlElementType"

    tokens = [
        DOT = '.'
        SEMICOLON = ';'
        COLON = ':'
        LBRACE = '{'
        RBRACE = '}'
        LT = '<'
        GT = '>'
        EQ = '='
        COMMA = ','

        IMPORT = 'import'
        METAQUERY = 'metaQuery'
        SQLMETADATA = 'sqlMetadata'
        PARAMETERS = 'parameters'
        STRING = 'String'
        BOOLEAN = 'Boolean'
        LONG = 'Long'
        DATE = 'Date'

        SPACE='regexp:\s+'
        LINE_COMMENT='regexp://.*'
        IDENTIFIER = 'regexp:\p{Alpha}\w*'
        LITERAL="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    ]

    mixin(".*ReferenceElement")="ru.bellski.lang.metasql.psi.impl.MetaSqlPsiReferenceImpl"
    implements(".*ReferenceElement")="ru.bellski.lang.metasql.psi.MetaSqlPsiReference"

    mixin("metadataClassAccess")="ru.bellski.lang.metasql.psi.impl.MetaSqlMetadataPsiReferenceImpl"
    implements("metadataClassAccess")="ru.bellski.lang.metasql.psi.MetaSqlMetadataPsiReference"
}

metaSqlFile ::= importList metaQuery

importList ::= importStatement*

/* IMPORT */

importStatement ::= 'import' importReferenceElement parametersAssign? ';'  {pin=1}

importReferenceElement ::= (IDENTIFIER (('.' IDENTIFIER)*)?)

metaQuery ::= 'metaQuery' IDENTIFIER? '{' metadataAssign? '}' {pin=1}

metadataAssign ::= 'sqlMetadata' '=' metadataClassAccess ';'
metadataClassAccess ::= IDENTIFIER;

parametersAssign ::= 'parameters' '=' '[' parameterVariable ']'
parameterVariable ::= sqlParameterTypeGroup IDENTIFIER

private sqlParameterTypeGroup ::= 'String' | 'Boolean' | 'Long' | 'Date'
{extends="typeElement"}

typeElement ::= codeReferenceElement

codeReferenceElement ::= IDENTIFIER referenceParameterList
referenceParameterList ::= ('<' typeElement '>')?






